# Generated by Django 5.2.15 on 2026-07-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jobapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_user',
            field=models.ForeignKey(blank=True, help_text='Assign an HR User to this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
