# Generated by Django 5.2.15 on 2026-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hrprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
    ]
