# Generated by Django 5.2.15 on 2026-07-08 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='hr_user',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='hr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('candidate', 'Candidate'), ('employee', 'Employee'), ('employer', 'Employer')], default='candidate', max_length=20),
        ),
    ]
