# Generated by Django 5.2.15 on 2026-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='hr_pics/'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
