# Generated by Django 5.2.15 on 2026-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hrprofile_profile_pic_hrprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
