# Generated by Django 5.2.15 on 2026-07-09 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobapplication_designation_jobapplication_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
