# Generated by Django 5.2.15 on 2026-07-09 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jobopening_hr_alter_jobopening_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
