# Generated by Django 5.2.15 on 2026-07-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobopening_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('hr', 'HR'), ('admin', 'Admin')], default='candidate', max_length=20),
        ),
    ]
